### ISSUE TITLE
Radar Chart Question

### ISSUE THREAD

**Issue by tinchobulen** [holtzy/D3-graph-gallery#18]
Hi @holtzy ! 

I'm trying to make a radarchart in R. 
It's about a frog's daily vocal activity. But I'm having some trouble (like always in R) with the script. 
my radarchart sequence must be between (0 ,2) and by 0.2. 
But when I try it the graph it is out of bounds.

Could you please give me a hand here?
I've attached my data.frame and r script.

cheers,

Martín.

[radar_chart.txt](https://github.com/holtzy/D3-graph-gallery/files/4108857/radar_chart.txt)

Script

read.csv("D:/Tesis/Gastros/grafico_circular.csv", header = T, sep = ";", dec = ".")-> G.chrys

library("fmsb")

colnames(G.chrys) <- c(24:1)

View(G.chrys)

#plot circular

windows()

radarchart(G.chrys, axistype = 1, caxislabels = seq(0,2,0.2), cglcol = "grey",vlcex = 0.8, cglty = 1, cglwd = 0.5,axislabcol = "grey", pcol = "black",plwd = 1.8, plty = 1)

**Comment by holtzy** [comment]
Hi,
This repo is about d3.js and I do not provide 1:1 explanations here, I just try to fix bugs!
All the best,
