### ISSUE TITLE
Hi, offline csv file dosn't work (same directory of full path)

### ISSUE THREAD

**Issue by rafi533** [holtzy/D3-graph-gallery#40]

**Comment by dgknca** [comment]
you should use a live-server. otherwise fetching data from a file won't work. you can use this extension: https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer

**Comment by holtzy** [comment]
Hi, thx for the feedback but I'm not sure what the problem is.

I've just tried to reproduce the piece of code of this blog post that uses `d3.csv` and it worked well.
https://www.d3-graph-gallery.com/graph/scatter_basic.html

Can you describe a bit more what the issue is? Thanks!
