### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by infogulch** [holtzy/D3-graph-gallery#83]
Hi! Nice set of sample charts, I especially appreciated the stacked area example. I was hoping to make a simple adaptation and re-publish some of the code for the stacked area example in a github template repo that I expect may be forked a lot. But seeing as this code does not have any published license, this may be a bad idea.

Do you intend to apply a general open-source license to this repo and the example code in particular? (If you do and are unsure what license is appropriate, perhaps https://choosealicense.com can help. If not that's fine too.)

#30 is related but the author closed it before any discussion occurred.

**Comment by holtzy** [comment]
Hi Joe,
Thanks for your message.

I have absolutely 0 knowledge on licensing and that's something I should be more interested in. 

But for now I have absolutely 0 bandwidth for that :(. So please use the code how you want, but just cite the URL of the gallery 🙏 

If you have any suggestion about how I should license appropriately, I'm interested.

**Comment by GabLeRoux** [comment]
I recommend using MIT license as it's quite permissive and will also protect you. If you're looking for more details or would like to compare licenses, you can have a look on https://www.tldrlegal.com/ or follow the guide here:
https://choosealicense.com/

If you're ok with MIT License, you can simply merge #98 👍

Feel free to close the PR and pick a different one if you prefer :)

**Comment by holtzy** [comment]
thanks!!!!!
