### ISSUE TITLE
gores from equirectangular image

### ISSUE THREAD

**Issue by herrpedro** [holtzy/D3-graph-gallery#92]
I'm a 360 photographer and I came across the Interrupted Sinusoidal Projection while i was searching for a way to print my images

https://www.jasondavies.com/maps/interrupted-sinusoidal/

is there a way for d3 to take a "good resolution" image and build 60 gores?

curiously didn't find this question here

hope it's not that dumb

thank you.

**Comment by holtzy** [comment]
Hi,
Definitely not a dumb question, but I have no idea how to do that sorry!
